### ISSUE TITLE
Dependency on flow?

### ISSUE THREAD

**Issue by chmac** [ephemer/meteor-css3d#3]
Looking at [this](https://github.com/ephemer/meteor-css3d/blob/master/css3d.js#L20) and wondering if there's a hidden dependency on a `flow` object having a `log` property which is a function. Guessing this is something y'all use internally at flowkey to handle logging...

**Comment by nerdmed** [comment]
hey @chmac, thanks for pointing out. Just removed the dependency. My partner @ephemer is on vacation. He will publish it to atmosphere as soon as he is back.
